In [1]:
print("abc");

[1] "abc"


In [2]:
print(12.5)

[1] 12.5


In [3]:
v <- 5:13

In [4]:
v

[1]  5  6  7  8  9 10 11 12 13

In [5]:
v <- 1:100

In [6]:
v

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [7]:
v <-  1.2 : 4.3

In [8]:
v

[1] 1.2 2.2 3.2 4.2

In [9]:
v <- 3.8:11.4

In [10]:
v

[1]  3.8  4.8  5.8  6.8  7.8  8.8  9.8 10.8

In [11]:
k<-seq(5, 9, by = 0.4)

In [12]:
k

[1] 5.0 5.4 5.8 6.2 6.6 7.0 7.4 7.8 8.2 8.6 9.0

In [13]:
k<-seq(0 ,100, by = 3)

In [14]:
k

[1]  0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
[26] 75 78 81 84 87 90 93 96 99

In [15]:
s <- c('apple','red',5,TRUE)

In [16]:
s

[1] "apple" "red"   "5"     "TRUE"

In [17]:
t <- c("Sun","Mon","Tue","Wed","Thurs","Fri","Sat")

In [18]:
t

[1] "Sun"   "Mon"   "Tue"   "Wed"   "Thurs" "Fri"   "Sat"

In [19]:
u <- t[c(2,3,6)]

In [20]:
u

[1] "Mon" "Tue" "Fri"

In [21]:
v <- t[c(TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE)]

In [22]:
v

[1] "Sun" "Fri"

In [23]:
c(TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE)

[1]  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

In [24]:
c

[1] 2000

In [25]:
x <- t[c(-2,-5)]

In [26]:
x

[1] "Sun" "Tue" "Wed" "Fri" "Sat"

In [27]:
y <- t[c(0,0,0,0,0,0,1)]

In [28]:
y

[1] "Sun"

In [29]:
v1 <- c(3,8,4,5,0,11)

In [30]:
v2 <- c(4,11,0,8,1,2)

In [31]:
x <- v1+v2

In [32]:
x

[1]  7 19  4 13  1 13

In [33]:
add.result <- v1+v2

In [34]:
add.result

[1]  7 19  4 13  1 13

In [35]:
x <- v1-v2

In [36]:
x

[1] -1 -3  4 -3 -1  9

In [37]:
x <- v1*v2
x

[1] 12 88  0 40  0 22

In [38]:
x <- v1/v2
x

[1] 0.7500000 0.7272727       Inf 0.6250000 0.0000000 5.5000000

In [39]:
x <- v1^v2
x

[1]         81 8589934592          1     390625          0        121

In [40]:
v1 <- c(3,8,4,5,0,11)
v2 <- c(4,11)

In [41]:
x <- v1+v2
x

[1]  7 19  8 16  4 22

In [43]:
v1 <- c(3,8,4,5,0,11,20)
v2 <- c(4,11)

In [44]:
x <- v1+v2
x

Warning message in v1 + v2:
“longer object length is not a multiple of shorter object length”

[1]  7 19  8 16  4 22 24

In [45]:
v <- c(3,8,4,5,0,11, -9, 304)

In [46]:
x <- sort(v)
x

[1]  -9   0   3   4   5   8  11 304

In [47]:
x <- sort(v, decreasing = TRUE)
x

[1] 304  11   8   5   4   3   0  -9

In [48]:
v <- c("Red","Blue","yellow","violet")

In [49]:
x <- sort(v)
x

[1] "Blue"   "Red"    "violet" "yellow"

In [50]:
x <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1)

In [51]:
x

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 119.1

In [52]:
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),list("green",12.3))

In [53]:
list_data

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[3]]
[[3]][[1]]
[1] "green"

[[3]][[2]]
[1] 12.3

In [54]:
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

In [55]:
names(list_data) 

[1] "1st Quarter"  "A_Matrix"     "A Inner list"

In [56]:
list_data

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3

In [57]:
list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),list("green",12.3))

In [58]:
list_data

[[1]]
[1] "Jan" "Feb" "Mar"

[[2]]
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

[[3]]
[[3]][[1]]
[1] "green"

[[3]][[2]]
[1] 12.3

In [59]:
print(list_data[1])

[[1]]
[1] "Jan" "Feb" "Mar"



In [60]:
print(list_data$A_Matrix)

NULL


In [62]:
list_data[3] <- "updated element"
print(list_data[3])

[[1]]
[1] "updated element"



In [63]:
list1 <- list(1,2,3)
list2 <- list("Sun","Mon","Tue")

In [64]:
mergex<- c(list1,list2)

In [65]:
mergex

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Sun"

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"

In [66]:
x <- list(1:5)

In [67]:
x

[[1]]
[1] 1 2 3 4 5

In [68]:
v1 <- unlist(list1)

In [69]:
v1

[1] 1 2 3