In [1]:
M <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [2]:
M <- matrix(c(1:9), nrow = 4, byrow = TRUE)
print(M)

Warning message in matrix(c(1:9), nrow = 4, byrow = TRUE):
“data length [9] is not a sub-multiple or multiple of the number of rows [4]”


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]    1    2    3


In [3]:
M <- matrix(c(1:12), nrow = 4, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [4]:
N <- matrix(c(3:14), nrow = 4, byrow = FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


In [5]:
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

In [6]:
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))
print(P)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [7]:
# Define the column and row names.
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

In [8]:
# Create the matrix.
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))

In [9]:
# Access the element at 3rd column and 1st row.
print(P[1,3])

[1] 5


In [10]:
# Access the element at 2nd column and 4th row.
print(P[4,2])

[1] 13


In [11]:
# Access only the  2nd row.
print(P[2,])

# Access only the 3rd column.
print(P[,3])

col1 col2 col3 
   6    7    8 
row1 row2 row3 row4 
   5    8   11   14 


In [12]:
# Create two 2x3 matrices.
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6


In [13]:
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [14]:
# Add the matrices.
result <- matrix1 + matrix2
cat("Result of addition","\n")
print(result)

Result of addition 
     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13   10


In [15]:
# Subtract the matrices
result <- matrix1 - matrix2
cat("Result of subtraction","\n")
print(result)

Result of subtraction 
     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5    2


In [16]:
# Create two 2x3 matrices.
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6


In [17]:
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [18]:
# Multiply the matrices.
result <- matrix1 * matrix2
cat("Result of multiplication","\n")
print(result)

Result of multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24


In [19]:
# Divide the matrices
result <- matrix1 / matrix2
cat("Result of division","\n")
print(result)

Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000
