In [1]:
M <- matrix(c(3:14), nrow = 4, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14


In [2]:
M <- matrix(c(1:9), nrow = 4, byrow = TRUE)
print(M)

Warning message in matrix(c(1:9), nrow = 4, byrow = TRUE):
“data length [9] is not a sub-multiple or multiple of the number of rows [4]”


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]    1    2    3


In [3]:
M <- matrix(c(1:12), nrow = 4, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [4]:
N <- matrix(c(3:14), nrow = 4, byrow = FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14


In [5]:
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

In [6]:
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))
print(P)

     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


In [7]:
# Define the column and row names.
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

In [8]:
# Create the matrix.
P <- matrix(c(3:14), nrow = 4, byrow = TRUE, dimnames = list(rownames, colnames))

In [9]:
# Access the element at 3rd column and 1st row.
print(P[1,3])

[1] 5


In [10]:
# Access the element at 2nd column and 4th row.
print(P[4,2])

[1] 13


In [11]:
# Access only the  2nd row.
print(P[2,])

# Access only the 3rd column.
print(P[,3])

col1 col2 col3 
   6    7    8 
row1 row2 row3 row4 
   5    8   11   14 


In [12]:
# Create two 2x3 matrices.
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6


In [13]:
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [14]:
# Add the matrices.
result <- matrix1 + matrix2
cat("Result of addition","\n")
print(result)

Result of addition 
     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13   10


In [15]:
# Subtract the matrices
result <- matrix1 - matrix2
cat("Result of subtraction","\n")
print(result)

Result of subtraction 
     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5    2


In [16]:
# Create two 2x3 matrices.
matrix1 <- matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6


In [17]:
matrix2 <- matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [18]:
# Multiply the matrices.
result <- matrix1 * matrix2
cat("Result of multiplication","\n")
print(result)

Result of multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24


In [19]:
# Divide the matrices
result <- matrix1 / matrix2
cat("Result of division","\n")
print(result)

Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000


In [20]:
x=matrix(1:9, nrow = 3, ncol = 3)

In [21]:
x

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [22]:
b=matrix(11,19, nrow = 3, ncol = 3)

In [23]:
b

[,1] [,2] [,3]
[1,] 11   11   11  
[2,] 11   11   11  
[3,] 11   11   11

In [24]:
x+b

[,1] [,2] [,3]
[1,] 12   15   18  
[2,] 13   16   19  
[3,] 14   17   20

In [25]:
x*b

[,1] [,2] [,3]
[1,] 11   44   77  
[2,] 22   55   88  
[3,] 33   66   99

In [26]:
x-b

[,1] [,2] [,3]
[1,] -10  -7   -4  
[2,]  -9  -6   -3  
[3,]  -8  -5   -2

In [27]:
x/b

[,1]       [,2]      [,3]     
[1,] 0.09090909 0.3636364 0.6363636
[2,] 0.18181818 0.4545455 0.7272727
[3,] 0.27272727 0.5454545 0.8181818

In [28]:
class(x)

[1] "matrix"

In [29]:
dim

function (x)  .Primitive("dim")

In [30]:
dim(x)

[1] 3 3

In [31]:
dim(b)

[1] 3 3

In [32]:
a=matrix(1:9, nrow = 3)

In [33]:
a

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [34]:
x <- matrix(1:9, nrow = 3, dimnames = list(c("X","Y","Z"), c("A","B","C")))

In [35]:
x

A B C
X 1 4 7
Y 2 5 8
Z 3 6 9

In [36]:
colnames(x)

[1] "A" "B" "C"

In [37]:
rownames(x)

[1] "X" "Y" "Z"

In [38]:
cbind(c(1,2,3),c(4,5,6))

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [39]:
x <- c(1,2,3,4,5,6)

In [40]:
class(x)

[1] "numeric"

In [41]:
dim(x) <- c(2,3)
x

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [42]:
class(x)

[1] "matrix"

In [43]:
x[c(1,2),c(2,3)] 

[,1] [,2]
[1,] 3    5   
[2,] 4    6

In [44]:
x[,] 

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [45]:
x[,] 

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [46]:
x[-1,] 

[1] 2 4 6

In [47]:
x[1,]

[1] 1 3 5

In [48]:
x[1,,drop=FALSE] 

[,1] [,2] [,3]
[1,] 1    3    5

In [49]:
class(x[1,,drop=FALSE])

[1] "matrix"

In [50]:
class(x)

[1] "matrix"

In [51]:
x[1:4]

[1] 1 2 3 4

In [52]:
x[c(TRUE, FALSE)]

[1] 1 3 5

In [53]:
x[x>5] 

[1] 6

In [54]:
 x[x%%2 == 0] 

[1] 2 4 6

In [55]:
x <- matrix(1:9, nrow = 3, dimnames = list(c("X","Y","Z"), c("A","B","C")))
x[,"A"]

X Y Z 
1 2 3

In [56]:
x[TRUE,c("A","C")]

A C
X 1 7
Y 2 8
Z 3 9

In [57]:
x[2:3,c("A","C")]

A C
Y 2 8
Z 3 9

In [58]:
x[2,2] <- 10

In [59]:
x[x<5] <- 0

In [60]:
t(x)  

X Y  Z
A 0  0 0
B 0 10 6
C 7  8 9

In [61]:
cbind(x, c(1, 2, 3)) 

A B  C  
X 0  0 7 1
Y 0 10 8 2
Z 0  6 9 3

In [62]:
 rbind(x,c(1,2,3))

A B  C
X 0  0 7
Y 0 10 8
Z 0  6 9
  1  2 3

In [63]:
 x <- x[1:2,]; x  

A B  C
X 0  0 7
Y 0 10 8

In [64]:
dim(x) <- c(3,2); x 

[,1] [,2]
[1,] 0    10  
[2,] 0     7  
[3,] 0     8

In [65]:
print(dim(x) <- c(1,6))

[1] 1 6
