In [2]:
vec <- c(3,4,5,6)  
vec

[1] 3 4 5 6

In [3]:
char_vec<-c("shubham","nishka","gunjan","sumit")  
char_vec

[1] "shubham" "nishka"  "gunjan"  "sumit"

In [4]:
logic_vec<-c(TRUE,FALSE,FALSE,TRUE)  
logic_vec

[1]  TRUE FALSE FALSE  TRUE

In [5]:
out_list<-list(vec,char_vec,logic_vec)  
out_list  

[[1]]
[1] 3 4 5 6

[[2]]
[1] "shubham" "nishka"  "gunjan"  "sumit"  

[[3]]
[1]  TRUE FALSE FALSE  TRUE

In [6]:
list_1<-list(1,2,3)  
list_2<-list("Shubham","Arpita","Vaishali")  
list_3<-list(c(1,2,3))  
list_4<-list(TRUE,FALSE,TRUE)  
list_1  
list_2  
list_3  
list_4  

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] "Shubham"

[[2]]
[1] "Arpita"

[[3]]
[1] "Vaishali"

[[1]]
[1] 1 2 3

[[1]]
[1] TRUE

[[2]]
[1] FALSE

[[3]]
[1] TRUE

In [7]:
list_data<-list("Shubham","Arpita",c(1,2,3,4,5),TRUE,FALSE,22.5,12L)  
print(list_data)  

[[1]]
[1] "Shubham"

[[2]]
[1] "Arpita"

[[3]]
[1] 1 2 3 4 5

[[4]]
[1] TRUE

[[5]]
[1] FALSE

[[6]]
[1] 22.5

[[7]]
[1] 12



In [8]:
# Creating a list containing a vector, a matrix and a list.  
list_data <- list(c("Shubham","Nishka","Gunjan"), matrix(c(40,80,60,70,90,80), nrow = 2),  
list("BCA","MCA","B.tech"))  

In [9]:
# Giving names to the elements in the list.  
names(list_data) <- c("Students", "Marks", "Course")  

In [10]:
# Show the list.  
print(list_data)  

$Students
[1] "Shubham" "Nishka"  "Gunjan" 

$Marks
     [,1] [,2] [,3]
[1,]   40   60   90
[2,]   80   70   80

$Course
$Course[[1]]
[1] "BCA"

$Course[[2]]
[1] "MCA"

$Course[[3]]
[1] "B.tech"




In [11]:
# Creating a list containing a vector, a matrix and a list.  
list_data <- list(c("Shubham","Arpita","Nishka"), matrix(c(40,80,60,70,90,80), nrow = 2),  
list("BCA","MCA","B.tech"))  

In [12]:
# Accessing the first element of the list.  
print(list_data[1])  

[[1]]
[1] "Shubham" "Arpita"  "Nishka" 



In [13]:
# Accessing the third element. The third element is also a list, so all its elements will be printed.  
print(list_data[3])  

[[1]]
[[1]][[1]]
[1] "BCA"

[[1]][[2]]
[1] "MCA"

[[1]][[3]]
[1] "B.tech"




In [14]:
# Creating a list containing a vector, a matrix and a list.  
list_data <- list(c("Shubham","Arpita","Nishka"), matrix(c(40,80,60,70,90,80), nrow = 2),list("BCA","MCA","B.tech"))  

In [15]:
# Giving names to the elements in the list.  
names(list_data) <- c("Student", "Marks", "Course")  

In [16]:
# Accessing the first element of the list.  
print(list_data["Student"])  
print(list_data$Marks)  
print(list_data)  

$Student
[1] "Shubham" "Arpita"  "Nishka" 

     [,1] [,2] [,3]
[1,]   40   60   90
[2,]   80   70   80
$Student
[1] "Shubham" "Arpita"  "Nishka" 

$Marks
     [,1] [,2] [,3]
[1,]   40   60   90
[2,]   80   70   80

$Course
$Course[[1]]
[1] "BCA"

$Course[[2]]
[1] "MCA"

$Course[[3]]
[1] "B.tech"




In [17]:
# Creating a list containing a vector, a matrix and a list.  
list_data <- list(c("Shubham","Arpita","Nishka"), matrix(c(40,80,60,70,90,80), nrow = 2),  
list("BCA","MCA","B.tech"))    

In [18]:
# Giving names to the elements in the list.  
names(list_data) <- c("Student", "Marks", "Course")  

In [19]:
# Adding element at the end of the list.  
list_data[4] <- "Moradabad"  
print(list_data[4])  

[[1]]
[1] "Moradabad"



In [20]:
# Removing the last element.  
list_data[4] <- NULL  

In [21]:
# Printing the 4th Element.  
print(list_data[4])  

$<NA>
NULL



In [22]:
# Updating the 3rd Element.  
list_data[3] <- "Masters of computer applications"  
print(list_data[3])  

$Course
[1] "Masters of computer applications"



In [24]:
# Creating lists.  
list1 <- list(10:20)  
print(list1)  

[[1]]
 [1] 10 11 12 13 14 15 16 17 18 19 20



In [25]:
list2 <-list(5:14)  
print(list2)  

[[1]]
 [1]  5  6  7  8  9 10 11 12 13 14



In [26]:
# Converting the lists to vectors.  
v1 <- unlist(list1)  
v2 <- unlist(list2)  

In [27]:
print(v1)  
print(v2)  

 [1] 10 11 12 13 14 15 16 17 18 19 20
 [1]  5  6  7  8  9 10 11 12 13 14


In [28]:
# adding the vectors  
result <- v1+v2  
print(result)  

Warning message in v1 + v2:
“longer object length is not a multiple of shorter object length”


 [1] 15 17 19 21 23 25 27 29 31 33 25


In [29]:
# Creating two lists.  
Even_list <- list(2,4,6,8,10)  
Odd_list <- list(1,3,5,7,9)  
      
# Merging the two lists.  
merged.list <- list(Even_list,Odd_list)  
      
# Printing the merged list.  
print(merged.list)  

[[1]]
[[1]][[1]]
[1] 2

[[1]][[2]]
[1] 4

[[1]][[3]]
[1] 6

[[1]][[4]]
[1] 8

[[1]][[5]]
[1] 10


[[2]]
[[2]][[1]]
[1] 1

[[2]][[2]]
[1] 3

[[2]][[3]]
[1] 5

[[2]][[4]]
[1] 7

[[2]][[5]]
[1] 9


